language: python
python:
- "3.6.5"
install: "pip install -r requirements.txt"
script:
- cd src && SECRET_KEY="whateverasdadadafakahhdwjkniwd15asd5a41d8wf158g54f154d5dd84awdaw44d" && python manage.py test || python3 manage.py test