# Generated by Django 2.2 on 2019-06-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickscooters',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
