# Generated by Django 2.2 on 2019-06-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0002_kickscooters_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickscooters',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
