# Generated by Django 2.2 on 2019-06-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0003_auto_20190606_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickscooters',
            name='feature_1',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='kickscooters',
            name='feature_2',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='kickscooters',
            name='feature_3',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
