# Generated by Django 2.2 on 2019-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0005_auto_20190606_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickscooters',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
            preserve_default=False,
        ),
    ]
