# Generated by Django 2.2 on 2019-06-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0006_kickscooters_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KickScooters',
            new_name='KickScooter',
        ),
    ]
