# Generated by Django 2.2 on 2019-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0007_auto_20190608_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickscooter',
            name='slug',
            field=models.SlugField(default='slug-default'),
            preserve_default=False,
        ),
    ]
