# Generated by Django 2.2 on 2019-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_scooter', '0008_kickscooter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickscooter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
